services:
  tf2-casual:
    image: ghcr.io/netwarlan/tf2
    environment:
      TF2_SERVER_HOSTNAME: "NETWAR TF2"
      TF2_SERVER_UPDATE_ON_START: true
      TF2_SERVER_MAP: "cp_well"
      TF2_SERVER_REMOTE_CFG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/tf2/tf2_casual.cfg"
    volumes:
      - ./data:/app/tf2
    restart: "unless-stopped"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      vlan:
        ipv4_address: 10.10.10.122
    cpuset: "3"

  tf2-casual-mvm:
    image: ghcr.io/netwarlan/tf2
    environment:
      TF2_SERVER_HOSTNAME: "NETWAR TF2 - MvM"
      TF2_SERVER_MAXPLAYERS: 32
      TF2_SERVER_UPDATE_ON_START: false
      TF2_SERVER_MAP: "mvm_ghost_town"
      TF2_SERVER_REMOTE_CFG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/tf2/tf2_mvm.cfg"
    volumes:
      - ./data:/app/tf2
    restart: "unless-stopped"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      vlan:
        ipv4_address: 10.10.10.123
    cpuset: "4"

networks:
  vlan:
    external: true